version: '3'
services:
  view:
    build:
      context: ./view
      dockerfile: Dockerfile
    ports:
      - "80:80"
  python-backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app.py
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - view
      - python-backend
